name: publish package to npm

on:
  workflow_dispatch:
    inputs:
      Environment:
        description: 'Enter Anything'
        required: false
        default: ''

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: yarn install
      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Make PR for Incremented Build Number
        continue-on-error: true
        uses: peter-evans/create-pull-request@v3
        with:
          branch: 'chore/increase_version'
          delete-branch: true
          base: master
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: increment version number'
          title: 'chore: increment version number'
          body: 'chore: increment version number'
          assignees: 'numandev1'

